django_stu/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import render,redirect
from .decorators import login_required

@login_required
def home(request):
    return render(request,'index.html')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include("user.urls")),
    path('',home),
    path('qd/',include("qd.urls"))
]

qd/urls.py
from django.urls import path,include
from .views import *

app_name='qd'
urlpatterns = [
    path('index/',QdView.as_view()),
    path('list/',QdList.as_view(),name='list'),
]

user/urls.py
from django.urls import path,include
from user.views import *

app_name ='user'
urlpatterns = [
    path('login/',login,name='login'),
    path('register/',RegisterView.as_view()),
    path('logout/',logout,name='logout'),
]

clazz/models.py
from django.db import models

# Create your models here.
class Clazz(models.Model):
    name = models.CharField(max_length=50)
    count = models.IntegerField()

    class Meta:
        db_table = "t_clazz"

qd/models.py
from django.db import models
from user.models import User
from clazz.models import Clazz
# Create your models here


class Qd(models.Model):
    stage = models.CharField(max_length=100)
    progress = models.CharField(max_length=100)
    code_num = models.IntegerField()
    bug_num = models.IntegerField()
    remark = models.CharField(max_length=500)
    uid = models.ForeignKey(User, on_delete=models.CASCADE,default=None)
    create_time = models.CharField(max_length=100,default=None)
    class Meta:
        db_table = "t_qd"

user/models.py
from django.db import models
from clazz.models import Clazz
# Create your models here.
class User(models.Model):
    class Meta:
        db_table = "t_user"
    id = models.AutoField(primary_key=True)
    uname = models.CharField(max_length=50)
    nick_name = models.CharField(max_length=50)
    pwd = models.CharField(max_length=50)
    sex = models.IntegerField()
    phone = models.IntegerField()
    clazz = models.ForeignKey(Clazz,on_delete=models.CASCADE)
    rid = models.IntegerField(default=1)

qd/forms.py
from django import forms

class QdForm(forms.Form):
    stage = forms.CharField(required=True,max_length=1)
    progress = forms.CharField(required=True,max_length=100)
    code_num = forms.IntegerField(required=True)
    bug_num = forms.IntegerField(required=False)
    remark = forms.CharField(required=False,max_length=500)

clazz/views.py
from django.shortcuts import render

# Create your views here.

qd/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.template.loader import get_template
from .forms import QdForm
from .models import Qd
from clazz.models import Clazz
from user.models import User
import time
from django.core.paginator import Paginator
def get_today():
    return time.strftime('%Y-%m-%d',time.localtime(time.time()))
# Create your views here.
class QdView(View):
    def get(self,request):
        return render(request,'qd/index.html')
    def post(self,request):
        form = QdForm(request.POST)
    
        if form.is_valid():
            user = User.objects.filter(id=request.session['uid']).first()
            Qd.objects.create( 	stage=form.cleaned_data['stage'],
                                progress=form.cleaned_data['progress'],
                                code_num=form.cleaned_data['code_num'],
                                bug_num=form.cleaned_data['bug_num'],
                                remark=form.cleaned_data['remark'],
                                uid = user,
                                create_time = get_today()
                            )
                        
            return render(request,'qd/index.html',{'msg':'签到成功！！'})
        else:
            return render(request,'qd/index.html',{'msg':'签到失败！！'})


class QdList(View):
    def get(self,request):
        if request.session.get('rid'):
            uid = request.session.get('uid')
            qds = Qd.objects.filter(uid=uid).order_by('-create_time')
            paginator = Paginator(qds, 5)
            page = request.GET.get('page')
            pager = paginator.get_page(page)
            return render(request,'qd/list.html',{'data':pager})
        else:
            cname = request.GET.get('cname')
            uname = request.GET.get('uname')
            create_time = request.GET.get('create_time')
            qds = Qd.objects
            if create_time:
                qds = qds.filter(create_time = create_time)
            if uname:
                user = User.objects.filter(nick_name = uname).first()
                qds = qds.filter(uid =user.id)
            if cname:
                clazz = Clazz.objects.filter(name = cname).first()
                uids = [u.id for u in User.objects.filter(clazz = clazz.id).all()]
                qds = qds.filter(uid__in=uids)
            qds = qds.all().order_by('-create_time')
            paginator = Paginator(qds, 5)
            page = request.GET.get('page')
            pager = paginator.get_page(page)
            return render(request,'qd/list_admin.html',{'data':pager})
    def post(self,request):
        pass

user/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render,redirect,reverse
from user.models import User
from clazz.models import Clazz
from django.views import View
# Create your views here.


def login(request):
    msg = None
    if 'POST' == request.method:
        # 获取从前台传来的uname
        uname = request.POST.get('uname')
        # 获取从前台传来的pwd
        pwd = request.POST.get('pwd')
        # 用前台传来的uname与pwd 去数据库中 匹配数据，因只要有一条匹配上就可以登录所以使用first()
        user = User.objects.filter(uname=uname, pwd=pwd).first()
        # 判断从数据库获取到数据
        if user:
            request.session['uid'] = user.id
            request.session['nick_name'] = user.nick_name
            request.session['rid'] = user.rid
            # 获取到数据后跳转主页
            return render(request, 'index.html')
        # 获取不到数据设置错误信息
        msg = '用户名或密码错误！'
    # GET请求与登录错误时跳转登录页面
    return render(request, 'login.html', {'msg': msg})

def logout(request):
    request.session.clear()
    return redirect('user:login')

class RegisterView(View):
    def get(self,request):
        clazzs = Clazz.objects.all()
        return render(request,'register.html',{'clazzs':clazzs})
    def post(self,request):
        # 获取从前台传来的uname
        uname = request.POST.get('uname')
        # 获取从前台传来的nick_name
        nick_name = request.POST.get('nick_name')
        # 获取从前台传来的phone
        phone = request.POST.get('phone')
        # 获取从前台传来的sex
        sex = 1 if request.POST.get('sex') == '女' else 0
        # 获取从前台传来的pwd
        pwd = request.POST.get('pwd')
        # 获取从前台传来的cid
        cid = request.POST.get('cid')
        # 通过CID获取clazz的对象
        clazz = Clazz.objects.filter(id=cid).first()
        user = User.objects.create(uname=uname,nick_name=nick_name,phone=phone,sex =sex,pwd=pwd,clazz=clazz)
        # 跳转到登录页面
        return redirect(reverse('user:login'))

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title%}{% endblock %}</title>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="shortcut icon" href="favicon_16.ico"/>
    <link rel="bookmark" href="favicon_16.ico"/>
    <!-- site css -->
    <link rel="stylesheet" href="{% static 'dist/css/site.min.css' %}">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="{% static 'dist/js/site.min.js' %}"></script>
    {% block css%}
        <style>
        body {
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #303641;
            color: #C1C3C6
        }
        </style>
    {% endblock %}
  </head>
  <body>
  {% block body%}
    <div class="container">
    
    

    </div>
    <div class="clearfix"></div>
    <br><br>
    <!--footer-->
  {% endblock %}
  </body>
  {% block script%}
  {% endblock %}
</html>

templates/index.html
{% extends 'index_base.html'%}
{% block title %} 主页 {% endblock %}


{% block panel_title %}主页 {% endblock %}
{% block panel_body%}
{% load static %}
<div class="content-row">
    <h2 class="content-row-title">Jumbotron</h2>
    <div class="row">
    <div class="col-md-6">
        <div class="jumbotron">
        <div class="jumbotron-photo">
            <img src="{% static ''%}dist/img/Jumbotron.jpg" />
        </div>
        <div class="jumbotron-contents">
            <h1>Implementing the HTML and CSS into your user interface project</h1>
            <h2>HTML Structure</h2>
            <p>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
            <h2>CSS Structure</h2>
            <p>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="jumbotron">
        <div id="carousel-content-row-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
            <li data-target="#carousel-content-row-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-content-row-generic" data-slide-to="1"></li>
            <li data-target="#carousel-content-row-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
            <div class="item active">
                <img src="{% static 'dist/img/slider1.jpg' %}">
            </div>
            <div class="item">
                <img src="{% static 'dist/img/slider2.jpg' %}">
            </div>
            <div class="item">
                <img src="{% static 'dist/img/slider3.jpg' %}">
            </div>
            </div>
            <a class="left carousel-control" href="#carousel-content-row-generic" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-content-row-generic" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
        <div class="jumbotron-contents">
            <h1>Implementing the HTML and CSS into your user interface project</h1>
            <h2>HTML Structure</h2>
            <p>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
            <h2>CSS Structure</h2>
            <p>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        </div>
        </div>
    </div>
    </div>
</div>
<!-- Thumbnails
                ================================================== -->
<div class="content-row">
    <h2 class="content-row-title">Thumbnails</h2>
    <div class="row">
    <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
        <img class="img-rounded" src="{% static ''%}dist/img/thumbnail-1.jpg">
        <div class="caption text-center">
            <h3>Thumbnail label</h3>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id ...</p>
            <p><a href="#" class="btn btn-warning" role="button">Button</a>  <a href="#" class="btn btn-default" role="button">Button</a>
            </p>
        </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
        <img class="img-rounded" src="{% static 'dist/img/thumbnail-2.jpg' %}">
        <div class="caption text-center">
            <h3>Thumbnail label</h3>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id ...</p>
            <p><a href="#" class="btn btn-warning" role="button">Button</a>  <a href="#" class="btn btn-default" role="button">Button</a>
            </p>
        </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
        <img class="img-rounded" src="{% static ''%}dist/img/thumbnail-3.jpg">
        <div class="caption text-center">
            <h3>Thumbnail label</h3>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id ...</p>
            <p><a href="#" class="btn btn-warning" role="button">Button</a>  <a href="#" class="btn btn-default" role="button">Button</a>
            </p>
        </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
        <img class="img-rounded" src="{% static ''%}dist/img/thumbnail-4.jpg">
        <div class="caption text-center">
            <h3>Thumbnail label</h3>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id ...</p>
            <p><a href="#" class="btn btn-warning" role="button">Button</a>  <a href="#" class="btn btn-default" role="button">Button</a>
            </p>
        </div>
        </div>
    </div>
    </div>
</div>
{% endblock %}

templates/index_base.html
{% extends 'base.html'%}
{% block css%} {% endblock %}
{% block body %}
    <nav role="navigation" class="navbar navbar-custom">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button data-target="#bs-content-row-navbar-collapse-5" data-toggle="collapse" class="navbar-toggle" type="button">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a href="#" class="navbar-brand">Django Study System</a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div id="bs-content-row-navbar-collapse-5" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
          
              <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">{% if request.session.nick_name %}{{ request.session.nick_name }}{% endif %} <b class="caret"></b></a>
                <ul role="menu" class="dropdown-menu">
                  <li class="dropdown-header">Setting</li>
                  <li><a href="#">Action</a></li>
                  <li class="divider"></li>
                  <li class="active"><a href="#">Separated link</a></li>
                  <li class="divider"></li>
                  <li class="disabled"><a href="{% url 'user:logout' %}">Signout</a></li>
                </ul>
              </li>
            </ul>

          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
    <!--header-->
    <div class="container-fluid">
    <!--documents-->
        <div class="row row-offcanvas row-offcanvas-left">
          <div class="col-xs-6 col-sm-3 sidebar-offcanvas" role="navigation">
            <ul class="list-group panel">
                <li class="list-group-item"><i class="glyphicon glyphicon-align-justify"></i> <b>SIDE PANEL</b></li>
                <li class="list-group-item"><input type="text" class="form-control search-query" placeholder="Search Something"></li>
                <li class="list-group-item"><a href="/"><i class="glyphicon glyphicon-home"></i>主页 </a></li>
                <li class="list-group-item"><a href="/qd/index/"><i class="glyphicon glyphicon-certificate"></i>签到 </a></li>
                <li class="list-group-item"><a href="list.html"><i class="glyphicon glyphicon-th-list"></i>班级信息</a></li>
                <li class="list-group-item"><a href="/qd/list/"><i class="glyphicon glyphicon-list-alt"></i>签到历史</a></li>
                <li class="list-group-item"><a href="alerts.html"><i class="glyphicon glyphicon-bell"></i>Alerts</a></li>
                <li class="list-group-item"><a href="timeline.html" ><i class="glyphicon glyphicon-indent-left"></i>Timeline</a></li>
                <li class="list-group-item"><a href="calendars.html" ><i class="glyphicon glyphicon-calendar"></i>Calendars</a></li>
                <li class="list-group-item"><a href="typography.html" ><i class="glyphicon glyphicon-font"></i>Typography</a></li>
                <li class="list-group-item"><a href="footers.html" ><i class="glyphicon glyphicon-minus"></i>Footers</a></li>
                <li class="list-group-item"><a href="panels.html" ><i class="glyphicon glyphicon-list-alt"></i>Panels</a></li>
                <li class="list-group-item"><a href="navs.html" ><i class="glyphicon glyphicon-th-list"></i>Navs</a></li>
                <li class="list-group-item"><a href="colors.html" ><i class="glyphicon glyphicon-tint"></i>Colors</a></li>
                <li class="list-group-item"><a href="flex.html" ><i class="glyphicon glyphicon-th"></i>Flex</a></li>
                <li class="list-group-item"><a href="login.html" ><i class="glyphicon glyphicon-lock"></i>Login</a></li>
                <li>
                  <a href="#demo3" class="list-group-item " data-toggle="collapse">Item 3  <span class="glyphicon glyphicon-chevron-right"></span></a>
                  <div class="collapse" id="demo3">
                    <a href="#SubMenu1" class="list-group-item" data-toggle="collapse">Subitem 1  <span class="glyphicon glyphicon-chevron-right"></span></a>
                    <div class="collapse list-group-submenu" id="SubMenu1">
                      <a href="#" class="list-group-item">Subitem 1 a</a>
                      <a href="#" class="list-group-item">Subitem 2 b</a>
                      <a href="#SubSubMenu1" class="list-group-item" data-toggle="collapse">Subitem 3 c <span class="glyphicon glyphicon-chevron-right"></span></a>
                      <div class="collapse list-group-submenu list-group-submenu-1" id="SubSubMenu1">
                        <a href="#" class="list-group-item">Sub sub item 1</a>
                        <a href="#" class="list-group-item">Sub sub item 2</a>
                      </div>
                      <a href="#" class="list-group-item">Subitem 4 d</a>
                    </div>
                    <a href="javascript:;" class="list-group-item">Subitem 2</a>
                    <a href="javascript:;" class="list-group-item">Subitem 3</a>
                  </div>
                </li>
                <li>
                  <a href="#demo4" class="list-group-item " data-toggle="collapse">Item 4  <span class="glyphicon glyphicon-chevron-right"></span></a>
                    <li class="collapse" id="demo4">
                      <a href="" class="list-group-item">Subitem 1</a>
                      <a href="" class="list-group-item">Subitem 2</a>
                      <a href="" class="list-group-item">Subitem 3</a>
                    </li>
                </li>
              </ul>
          </div>
          <div class="col-xs-12 col-sm-9 content">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title"><a href="javascript:void(0);" class="toggle-sidebar"><span class="fa fa-angle-double-left" data-toggle="offcanvas" title="Maximize Panel"></span></a>{% block panel_title%}{% endblock %}</h3>
              </div>
              <div class="panel-body">
              {% block panel_body %}{% endblock %}
              </div><!-- panel body -->
            </div>
        </div><!-- content -->
      </div>
    </div>
    <!--footer-->
{% endblock %}

templates/page.html
{% if data.object_list %}
    <ul class="pagination">
        <li>
            <a href="?page=1">
                <span>首页</span>
            </a>
        </li>
        {% if data.has_previous %}
            <li>
                <a href="?page={{ data.previous_page_number }}">
                    <span>上一页</span>
                </a>
            </li>
        {% endif %}
        {% for pg in data.paginator.page_range%}
            {% if pg == data.number %}
                <li class="active"><a href="#">{{ pg }}</a></li>
            {% else %}
                <li><a class="pagination__number" href="?page={{ pg }}">{{ pg }}</a></li>
            {% endif %}
        {% endfor %}
        {% if data.has_next %}
            <li>
                <a href="?page={{ data.next_page_number }}">
                    <span>下一页</span>
                </a>
            </li>
        {% endif %}
        <li>
            <a href="?page={{ data.paginator.num_pages }}">
                <span>末页</span>
            </a>
        </li>
    </ul>
{% endif %}

templates/qd/index.html
{% extends 'index_base.html'%}
{% block title %} 签到 {% endblock %}


{% block panel_title %} 签到 {% endblock %}
{% block panel_body%}
{% load static %}
<div class="content-row">
  <div class="panel-body">
      <form novalidate="" role="form" class="form-horizontal" action='/qd/index/' method="post">
        {% csrf_token %}
        <div class="form-group">
          <label class="col-md-2 control-label">阶段：</label>
          <div class="col-md-10">
            <input type="text" required="" placeholder="阶段信息" id="title" class="form-control" name="stage">
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-2 control-label">进度：</label>
          <div class="col-md-10">
            <input type="text" required="" placeholder="进度" id="subject" class="form-control" name="progress">
          </div>
        </div>
         <div class="form-group">
          <label class="col-md-2 control-label">Code数</label>
          <div class="col-md-10">
            <input type="text" required="" placeholder="Code数" id="subject" class="form-control" name="code_num">
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-2 control-label">Bug数</label>
          <div class="col-md-10">
            <input type="text" required="" placeholder="Bug数" id="subject" class="form-control" name="bug_num">
          </div>
        </div>

        <div class="form-group">
          <label class="col-md-2 control-label" for="description">备注</label>
          <div class="col-md-10">
            <textarea required="" class="form-control" placeholder="备注信息" rows="10" cols="30" id="description" name="description" name='remark'></textarea>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <button class="btn btn-info" type="submit">提 交</button>
          </div>
          {% if msg %}
            {{ msg }}
          {% endif %}
        </div>
      </form>
    </div>
</div>
{% endblock %}

templates/qd/list.html
{% extends 'index_base.html'%}

{% block title %} 签到历史 {% endblock %}


{% block panel_title %} 签到历史 {% endblock %}
{% load static %}
{% block panel_body%}
<div class="content-row">
  <table class="table table-bordered table-striped">
    {% comment %} <colgroup>
      <col class="col-xs-1">
      <col class="col-xs-7">
    </colgroup> {% endcomment %}
    <thead>
      <tr>
        <th>编号</th>
        <th>姓名</th>
        <th>章节</th>
        <th>进度</th>
        <th>code数</th>
        <th>bug数</th>
        <th>签到时间</th>
        <th>备注</th>
      </tr>
    </thead>
      {% for q in data.object_list %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ request.session.nick_name }}</td>
          <td>{{ q.stage }}</td>
          <td>{{ q.progress }}</td>
          <td>{{ q.code_num }}</td>
          <td>{{ q.bug_num }}</td>
          <td>{{ q.create_time }}</td>
          <td>{{ q.remark }}</td>
        </tr>
      {% endfor %}
                
  </table>
    {% include 'page.html' %}
</div>
{% endblock %}

templates/qd/list_admin.html
{% extends 'index_base.html'%}

{% block title %} 签到历史 {% endblock %}


{% block panel_title %} 签到历史 {% endblock %}
{% load static %}
{% block panel_body%}
<div class="content-row">
    <form role="form" action='{% url "qd:list" %}' method='get'>
      <div class="form-group col-md-3">
        <input name="cname" type="text" class="form-control" placeholder="班级">
      </div>
       <div class="form-group col-md-3">
        <input name="uname" type="text" class="form-control" placeholder="姓名">
      </div>
       <div class="form-group col-md-3">
        <input name="create_time" type="date" class="form-control" placeholder="日期">
      </div>
       <div class="form-group col-md-3">
        <input type="submit" class="btn btn-primary" value="查 询">
        <input type="button" class="btn btn-info" value="重 置">
      </div>
    </from>
</div>
<div class="content-row">
  <table class="table table-bordered table-striped">
    {% comment %} <colgroup>
      <col class="col-xs-1">
      <col class="col-xs-7">
    </colgroup> {% endcomment %}
    <thead>
      <tr>
        <th>编号</th>
        <th>姓名</th>
        <th>章节</th>
        <th>进度</th>
        <th>code数</th>
        <th>bug数</th>
        <th>签到时间</th>
        <th>备注</th>
      </tr>
    </thead>
      {% for q in data.object_list %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ q.uid.nick_name }}</td>
          <td>{{ q.stage }}</td>
          <td>{{ q.progress }}</td>
          <td>{{ q.code_num }}</td>
          <td>{{ q.bug_num }}</td>
          <td>{{ q.create_time }}</td>
          <td>{{ q.remark }}</td>
        </tr>
      {% endfor %}
                
  </table>
    {% include 'page.html' %}
</div>
{% endblock %}

templates/register.html
{% extends 'base.html'%}
{% block title %}
注册
{% endblock  %}

{% block body %}
      <form class="form-signin" role="form" action="/user/register/" method="post">
        {% csrf_token %}
        <h3 class="form-signin-heading">注 册</h3>
        <div class="form-group">
          <div class="input-group">
            <div class="input-group-addon">
              <i class="glyphicon glyphicon-user"></i>
            </div>
            <input type="text" class="form-control" name="uname" id="username" placeholder="用户名" autocomplete="off" />
          </div>
        </div>

        <div class="form-group">
          <div class="input-group">
            <div class="input-group-addon">
              <i class="glyphicon glyphicon-user"></i>
            </div>
            <input type="text" class="form-control" name="nick_name" id="username" placeholder="昵称" autocomplete="off" />
          </div>
        </div>
        <div class="form-group">
          <div class="input-group">
            <div class="input-group-addon">
              <i class="glyphicon glyphicon-lock"></i>
            </div>
            <input type="password" class="form-control" name="pwd" id="username" placeholder="密码" autocomplete="off" />
          </div>
        </div>
        <div class="form-group">
          <div class="input-group">
            <div class="input-group-addon">
              <i class="glyphicon glyphicon-gift"></i>
            </div>
            <input type="text" class="form-control" name="sex" id="username" placeholder="性别" autocomplete="off" />
          </div>
        </div>

        <div class="form-group">
          <div class="input-group">
            <div class="input-group-addon">
              <i class=" glyphicon glyphicon-phone "></i>
            </div>
            <input type="password" class="form-control" name="phone" id="password" placeholder="电话" autocomplete="off" />
          </div>
        </div>

        <button class="btn btn-lg btn-primary btn-block" type="submit">注 册</button>
      </form>
{% endblock  %}

user/templates/login.html
{% extends 'base.html'%}
{% block title %}
登录
{% endblock  %}

{% block body %}
      <form class="form-signin" role="form" action="/user/login/" method="post">
        {% csrf_token %}
        <h3 class="form-signin-heading">登 录</h3>
        <div class="form-group">
          <div class="input-group">
            <div class="input-group-addon">
              <i class="glyphicon glyphicon-user"></i>
            </div>
            <input type="text" class="form-control" name="uname" id="username" placeholder="用户名" autocomplete="off" />
          </div>
        </div>

        <div class="form-group">
          <div class="input-group">
            <div class="input-group-addon">
              <i class=" glyphicon glyphicon-lock "></i>
            </div>
            <input type="password" class="form-control" name="pwd" id="password" placeholder="密码" autocomplete="off" />
          </div>
        </div>

        <label class="checkbox">
          <input type="checkbox" value="remember-me"> &nbsp Remember me
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">登 录</button>
          {% if msg %}
            <div class="alert alert-warning alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <strong>Warning!</strong> {{msg}}
                      </div>
        {% endif %}
      </form>
{% endblock  %}